# Generated by Django 4.2.1 on 2023-05-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empl', '__first__'),
        ('org', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('num', models.IntegerField()),
                ('slug', models.SlugField(max_length=64)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.department')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('is_best', models.BooleanField(default=False)),
                ('percent', models.FloatField(default=0.0)),
                ('slug', models.SlugField(max_length=64)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cal.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slug', models.SlugField(max_length=64)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='cal.version')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='empl.employee')),
                ('fills_with', models.ManyToManyField(related_name='fills_with', to='empl.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='org.shift')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cal.workday')),
            ],
        ),
    ]
