# Generated by Django 4.2.1 on 2023-05-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_shift_initial_start_date_alter_shift_hours'),
        ('empl', '0003_employee_active_employee_hire_date_and_more'),
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='employee_list',
            field=models.ManyToManyField(related_name='schedules', to='empl.employee'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift_list',
            field=models.ManyToManyField(related_name='schedules', to='org.shift'),
        ),
    ]
