# Generated by Django 4.2.1 on 2023-05-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_schedule_employee_list_schedule_shift_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
