# Generated by Django 4.2.1 on 2023-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_schedule_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_count',
            field=models.IntegerField(default=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workday',
            name='sd_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(),
        ),
    ]
