# Generated by Django 4.2.1 on 2023-05-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_schedule_day_count_workday_sd_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.IntegerField(choices=[(0, 'Discarded'), (1, 'Draft'), (2, 'Published')], default=1),
        ),
    ]
