# Generated by Django 4.2.1 on 2023-05-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0003_employee_active_employee_hire_date_and_more'),
        ('cal', '0005_version_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='empl.employee'),
        ),
    ]
