# Generated by Django 4.2.1 on 2023-05-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_alter_slot_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='prd_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='wk_id',
            field=models.IntegerField(null=True),
        ),
    ]
