# Generated by Django 4.2.1 on 2023-05-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_alter_workday_prd_id_alter_workday_wk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='wd_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
