# Generated by Django 4.2.1 on 2023-05-24 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0011_remove_templateddayoffset_name'),
        ('cal', '0010_schedule_tdoset_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='fills_with',
        ),
        migrations.CreateModel(
            name='FillsWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_in_week', models.IntegerField(default=0)),
                ('hours_in_period', models.IntegerField(default=0)),
                ('hours_needed', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills_with', to='empl.employee')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills_with', to='cal.slot')),
            ],
        ),
    ]
