# Generated by Django 4.2.1 on 2023-05-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_remove_slot_fills_with_fillswith'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillswith',
            name='exceeds_period_fte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fillswith',
            name='exceeds_week_fte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fillswith',
            name='other_on_conflicting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fillswith',
            name='other_on_day',
            field=models.BooleanField(default=False),
        ),
    ]
