# Generated by Django 4.2.1 on 2023-05-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0016_alter_templateslot_shift'),
        ('cal', '0014_alter_workday_options_fillswith_is_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='template_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templated_to', to='empl.employee'),
        ),
    ]
