# Generated by Django 4.2.1 on 2023-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0015_slot_template_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='option_count',
            field=models.IntegerField(default=0),
        ),
    ]
