# Generated by Django 4.2.1 on 2023-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0017_alter_templateslot_options_employee_initials'),
        ('cal', '0016_slot_option_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillswith',
            options={'ordering': ('hours_in_period',)},
        ),
        migrations.RenameField(
            model_name='fillswith',
            old_name='hours_needed',
            new_name='hours_needed_in_period',
        ),
        migrations.AddField(
            model_name='fillswith',
            name='hours_needed_in_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='fillswith',
            unique_together={('employee', 'slot')},
        ),
    ]
