# Generated by Django 4.2.1 on 2023-05-25 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_alter_fillswith_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillswith',
            options={'ordering': ('-hours_needed_in_period',)},
        ),
    ]
