# Generated by Django 4.2.1 on 2023-05-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_alter_timephase_position'),
        ('empl', '0018_remove_employee_time_pref_employee_phase_pref'),
        ('cal', '0018_alter_fillswith_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('shift', 'workday'), ('workday', 'employee')},
        ),
    ]
