# Generated by Django 4.2.1 on 2023-05-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0019_alter_slot_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['workday__date', 'shift__start_time']},
        ),
    ]
