# Generated by Django 4.2.1 on 2023-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0020_alter_slot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillswith',
            name='has_pto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fillswith',
            name='has_tdo',
            field=models.BooleanField(default=False),
        ),
    ]
