# Generated by Django 4.2.1 on 2023-05-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0024_slot_is_one_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='state',
            field=models.CharField(choices=[('N', 'Normal'), ('T', 'Turnaround'), ('O', 'Overtime'), ('P', 'PTO Conflict')], default='N', max_length=1),
        ),
    ]
