# Generated by Django 4.2.1 on 2023-05-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0025_alter_slot_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='n_disliked_one_offs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='n_disliked_shifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='version',
            name='n_unfavorables',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slot',
            name='state',
            field=models.CharField(choices=[('N', 'Normal'), ('T', 'Turnaround'), ('O', 'Overtime'), ('P', 'PTO Conflict'), ('1', 'One Off')], default='N', max_length=1),
        ),
    ]
