# Generated by Django 4.2.1 on 2023-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0026_version_n_disliked_one_offs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='n_mistemplated',
            field=models.IntegerField(default=0),
        ),
    ]
