# Generated by Django 4.2.1 on 2023-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0029_version_n_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='state',
            field=models.CharField(choices=[('N', 'Normal'), ('T', 'Turnaround'), ('O', 'Overtime'), ('P', 'PTO Conflict'), ('D', 'TDO Conflict'), ('1', 'One Off')], default='N', max_length=1),
        ),
    ]
