# Generated by Django 4.2.1 on 2023-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0033_alter_slot_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='state',
            field=models.CharField(choices=[('E', 'Empty'), ('N', 'Normal'), ('T', 'Turnaround'), ('O', 'Overtime'), ('U', 'Unfavorable'), ('P', 'PTO Conflict'), ('D', 'TDO Conflict'), ('1', 'One Off'), ('M', 'Mistemplated'), ('S', 'Disliked')], default=('E', 'N'), max_length=10),
        ),
    ]
