# Generated by Django 4.2.1 on 2023-05-29 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0034_alter_slot_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('delta_n_unfavorables', models.IntegerField(default=0)),
                ('delta_n_mistemplated', models.IntegerField(default=0)),
                ('delta_n_disliked_one_offs', models.IntegerField(default=0)),
                ('delta_n_disliked_shifts', models.IntegerField(default=0)),
                ('delta_n_empty', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cal.version')),
            ],
            options={
                'ordering': ('-event_time',),
            },
        ),
    ]
