# Generated by Django 4.2.1 on 2023-06-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0035_transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fillswith',
            unique_together=set(),
        ),
    ]
