# Generated by Django 4.2.1 on 2023-06-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0036_alter_fillswith_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='state',
            field=models.CharField(choices=[('E', 'Empty'), ('N', 'Normal'), ('T', 'Turnaround'), ('<', 'Blocked by Previous'), ('>', 'Blocked by Next'), ('O', 'Overtime'), ('U', 'Unfavorable'), ('P', 'PTO Conflict'), ('D', 'TDO Conflict'), ('1', 'One Off'), ('M', 'Mistemplated'), ('S', 'Disliked')], default=('E', 'N'), max_length=10),
        ),
        migrations.DeleteModel(
            name='WeekSummary',
        ),
    ]
