# Generated by Django 4.2.1 on 2023-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0037_alter_slot_state_delete_weeksummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillswith',
            options={'ordering': ('state',)},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='employee_list',
            new_name='employees',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='pto_list',
            new_name='pto_requests',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='shift_list',
            new_name='shifts',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='exceeds_period_fte',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='exceeds_week_fte',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='has_pto',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='has_tdo',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='hours_in_period',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='hours_needed_in_period',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='hours_needed_in_week',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='is_allowed',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='is_assigned',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='other_on_conflicting',
        ),
        migrations.RemoveField(
            model_name='fillswith',
            name='other_on_day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tdoset_list',
        ),
        migrations.AddField(
            model_name='fillswith',
            name='state',
            field=models.CharField(choices=[('E', 'Empty'), ('N', 'Normal'), ('T', 'Turnaround'), ('<', 'Blocked by Previous'), ('>', 'Blocked by Next'), ('O', 'Overtime'), ('U', 'Unfavorable'), ('P', 'PTO Conflict'), ('D', 'TDO Conflict'), ('1', 'One Off'), ('M', 'Mistemplated'), ('S', 'Disliked')], default=('E', 'N'), max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
