# Generated by Django 4.2.1 on 2023-06-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0039_alter_fillswith_state_alter_slot_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='state',
            field=models.JSONField(blank=True, default=['NA']),
            preserve_default=False,
        ),
    ]
