# Generated by Django 4.2.1 on 2023-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0041_alter_slot_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillswith',
            name='state',
            field=models.CharField(choices=[('A', 'Allowed'), ('W', 'Blocked by Week FTE'), ('P', 'Blocked by Period FTE'), ('D', 'Blocked by Other on Day'), ('V', 'Blocked by Other on Conflicting'), ('N', 'Blocked by Other on Conflicting'), ('T', 'Blocked by TDO'), ('O', 'Blocked by PTO')], default='A', max_length=10),
        ),
    ]
