# Generated by Django 4.2.1 on 2023-06-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0042_alter_fillswith_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillswith',
            name='state_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
