# Generated by Django 4.2.1 on 2023-06-05 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0027_alter_training_is_available'),
        ('cal', '0043_fillswith_state_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='org.department'),
        ),
    ]
