# Generated by Django 4.2.1 on 2023-05-21 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empl', '0002_employee_linked_account'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='linked_accounts',
            field=models.ManyToManyField(related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='empl.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='org.shift')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='trained',
            field=models.ManyToManyField(related_name='shifts_trained', through='org.Training', to='empl.employee'),
        ),
    ]
