# Generated by Django 4.2.1 on 2023-05-21 04:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_organization_linked_accounts_training_shift_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='initial_start_date',
            field=models.DateField(default=datetime.date(2017, 1, 1)),
        ),
        migrations.AlterField(
            model_name='shift',
            name='hours',
            field=models.IntegerField(choices=[(2, 2), (4, 4), (6, 6), (8, 8), (10, 10), (12, 12)], default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
