# Generated by Django 4.2.1 on 2023-05-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_shift_initial_start_date_alter_shift_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='weekdays',
            field=models.CharField(choices=[('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('A', 'Saturday')], default='SMTWRFA', max_length=7),
        ),
    ]
