# Generated by Django 4.2.1 on 2023-05-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_alter_shift_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='sentiment_qual',
            field=models.IntegerField(choices=[(1, 'Strongly Dislike'), (2, 'Dislike'), (3, 'Neutral'), (4, 'Prefer'), (5, 'Strongly Prefer')], default=3),
        ),
        migrations.AddField(
            model_name='training',
            name='sentiment_quant',
            field=models.IntegerField(default=0),
        ),
    ]
