# Generated by Django 4.2.1 on 2023-05-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_department_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
