# Generated by Django 4.2.1 on 2023-05-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_alter_department_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='template_week_count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='image_url',
            field=models.CharField(default='static/img/ui/rph-workspace.png', max_length=200, null=True),
        ),
    ]
