# Generated by Django 4.2.1 on 2023-05-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_department_template_week_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='template_week_count',
        ),
        migrations.AddField(
            model_name='department',
            name='template_week_count_full_time',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='department',
            name='template_week_count_part_time',
            field=models.IntegerField(default=3),
        ),
    ]
