# Generated by Django 4.2.1 on 2023-05-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_remove_department_template_week_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='time_phase',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
