# Generated by Django 4.2.1 on 2023-05-25 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_shift_time_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=128, null=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('max_hour', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='time_phase',
        ),
        migrations.AddField(
            model_name='shift',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='org.timephase'),
        ),
    ]
