# Generated by Django 4.2.1 on 2023-05-25 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_timephase_remove_shift_time_phase_shift_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='timephase',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_phases', to='org.organization'),
        ),
    ]
