# Generated by Django 4.2.1 on 2023-05-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_timephase_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timephase',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
