# Generated by Django 4.2.1 on 2023-05-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0016_remove_departmentnotification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentnotification',
            name='message',
            field=models.TextField(),
        ),
    ]
