# Generated by Django 4.2.1 on 2023-06-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0022_remove_department_template_week_count_full_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timephase',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
