# Generated by Django 4.2.1 on 2023-06-01 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0023_alter_timephase_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timephase',
            name='max_hour',
        ),
        migrations.AddField(
            model_name='timephase',
            name='max_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
