# Generated by Django 4.2.1 on 2023-06-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0025_alter_department_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ('-sentiment_qual', 'sentiment_quant')},
        ),
    ]
