# Generated by Django 4.2.1 on 2023-06-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0026_alter_training_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
