# Generated by Django 4.2.1 on 2023-06-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0027_alter_training_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timephase',
            name='position',
            field=models.SmallIntegerField(),
        ),
    ]
