# Generated by Django 4.2.1 on 2023-06-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0028_alter_timephase_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='sentiment_qual',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Strongly Dislike'), (4, 'Dislike'), (3, 'Neutral'), (2, 'Prefer'), (1, 'Strongly Prefer')], default=3, help_text="The 'in general' value for how the employee feels about this shift, regardless of how they feel about other shifts."),
        ),
    ]
