# Generated by Django 4.2.1 on 2023-05-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_alter_department_image_url'),
        ('empl', '0003_employee_active_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.IntegerField()),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_slots', to='empl.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_slots', to='org.shift')),
            ],
            options={
                'unique_together': {('employee', 'sd_id', 'active')},
            },
        ),
    ]
