# Generated by Django 4.2.1 on 2023-05-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0004_templateslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateddayoff',
            name='active',
        ),
        migrations.RemoveField(
            model_name='templateddayoff',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='templateddayoff',
            name='employee',
        ),
        migrations.CreateModel(
            name='TemplatedDayOffSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templated_day_off_sets', to='empl.employee')),
            ],
            options={
                'unique_together': {('employee', 'name', 'active')},
            },
        ),
        migrations.AddField(
            model_name='templateddayoff',
            name='tdo_set',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='templated_days_off', to='empl.templateddayoffset'),
            preserve_default=False,
        ),
    ]
