# Generated by Django 4.2.1 on 2023-05-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0006_alter_templateddayoff_tdo_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateddayoff',
            name='tdo_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='empl.templateddayoffset'),
        ),
    ]
