# Generated by Django 4.2.1 on 2023-05-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0008_alter_templateddayoffset_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templateddayoffset',
            unique_together=set(),
        ),
    ]
