# Generated by Django 4.2.1 on 2023-05-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0009_alter_templateddayoffset_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateddayoffset',
            name='days',
            field=models.CharField(default=0, max_length=84),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TemplatedDayOff',
        ),
    ]
