# Generated by Django 4.2.1 on 2023-05-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0010_templateddayoffset_days_delete_templateddayoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateddayoffset',
            name='name',
        ),
    ]
