# Generated by Django 4.2.1 on 2023-05-24 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_shift_time_phase'),
        ('empl', '0011_remove_templateddayoffset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSlotSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('assignments', models.JSONField(default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_slots', to='empl.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_slots', to='org.shift')),
            ],
            options={
                'unique_together': {('employee', 'effective_date', 'active')},
            },
        ),
        migrations.DeleteModel(
            name='TemplateSlot',
        ),
    ]
