# Generated by Django 4.2.1 on 2023-05-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0012_templateslotset_delete_templateslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateslotset',
            name='shift',
        ),
    ]
