# Generated by Django 4.2.1 on 2023-05-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0013_remove_templateslotset_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateslotset',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_slot_sets', to='empl.employee'),
        ),
    ]
