# Generated by Django 4.2.1 on 2023-05-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_shift_time_phase'),
        ('empl', '0014_alter_templateslotset_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateslotset',
            name='assignments',
        ),
        migrations.CreateModel(
            name='TemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.IntegerField()),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='org.shift')),
                ('slot_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='empl.templateslotset')),
            ],
            options={
                'abstract': False,
                'unique_together': {('sd_id', 'slot_set')},
            },
        ),
    ]
