# Generated by Django 4.2.1 on 2023-05-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_shift_time_phase'),
        ('empl', '0015_remove_templateslotset_assignments_templateslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateslot',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='org.shift'),
        ),
    ]
