# Generated by Django 4.2.1 on 2023-05-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0016_alter_templateslot_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templateslot',
            options={'ordering': ('sd_id',)},
        ),
        migrations.AddField(
            model_name='employee',
            name='initials',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
