# Generated by Django 4.2.1 on 2023-05-25 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_alter_timephase_position'),
        ('empl', '0017_alter_templateslot_options_employee_initials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='time_pref',
        ),
        migrations.AddField(
            model_name='employee',
            name='phase_pref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='org.timephase'),
        ),
    ]
