# Generated by Django 4.2.1 on 2023-05-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0025_alter_slot_state'),
        ('empl', '0018_remove_employee_time_pref_employee_phase_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptorequest',
            name='workdays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pto_requests', to='cal.workday'),
        ),
    ]
