# Generated by Django 4.2.1 on 2023-05-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0026_version_n_disliked_one_offs_and_more'),
        ('empl', '0020_remove_ptorequest_workdays_ptorequest_workdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptorequest',
            name='workdays',
            field=models.ManyToManyField(related_name='pto_requests', to='cal.workday'),
        ),
    ]
