# Generated by Django 4.2.1 on 2023-05-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0021_alter_ptorequest_workdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='template_size',
            field=models.IntegerField(choices=[(2, 'Weeks 2'), (3, 'Weeks 3')], default=2),
        ),
    ]
