# Generated by Django 4.2.1 on 2023-05-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0022_employee_template_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='trade_one_offs',
            field=models.BooleanField(default=True),
        ),
    ]
