# Generated by Django 4.2.1 on 2023-05-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0024_templateddayoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pto_hours_size',
            field=models.IntegerField(default=10),
        ),
    ]
