# Generated by Django 4.2.1 on 2023-05-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0020_alter_training_sentiment_qual_and_more'),
        ('empl', '0026_templateslot_shift_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_id', models.IntegerField()),
                ('state', models.CharField(choices=[('A', 'Base Available'), ('D', 'Defined Slot'), ('G', 'Generic Slot'), ('T', 'Templated Day Off')], default='A', max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_templates', to='empl.employee')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_templates', to='org.shift')),
            ],
        ),
        migrations.CreateModel(
            name='DayTemplateSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_template_sets', to='empl.employee')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='templateslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='templateslot',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='templateslot',
            name='shift_options',
        ),
        migrations.RemoveField(
            model_name='templateslot',
            name='slot_set',
        ),
        migrations.AlterUniqueTogether(
            name='templateslotset',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='templateslotset',
            name='employee',
        ),
        migrations.DeleteModel(
            name='DayOffSlotTemplate',
        ),
        migrations.DeleteModel(
            name='TemplateSlot',
        ),
        migrations.DeleteModel(
            name='TemplateSlotSet',
        ),
        migrations.AddField(
            model_name='daytemplate',
            name='shift_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_templates', to='empl.daytemplateset'),
        ),
        migrations.AlterUniqueTogether(
            name='daytemplate',
            unique_together={('employee', 'sd_id', 'shift_set')},
        ),
    ]
