# Generated by Django 4.2.1 on 2023-05-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0020_alter_training_sentiment_qual_and_more'),
        ('empl', '0027_daytemplate_daytemplateset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daytemplate',
            old_name='shift_set',
            new_name='collection',
        ),
        migrations.AlterUniqueTogether(
            name='daytemplate',
            unique_together={('employee', 'sd_id', 'collection')},
        ),
        migrations.AddField(
            model_name='daytemplate',
            name='shift_options',
            field=models.ManyToManyField(related_name='day_template_options', to='org.shift'),
        ),
    ]
