# Generated by Django 4.2.1 on 2023-05-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0020_alter_training_sentiment_qual_and_more'),
        ('empl', '0028_rename_shift_set_daytemplate_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytemplate',
            name='sd_id_list',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daytemplate',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_templates', to='empl.daytemplateset'),
        ),
        migrations.AlterField(
            model_name='daytemplate',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_templates', to='org.shift'),
        ),
    ]
