# Generated by Django 4.2.1 on 2023-05-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0029_daytemplate_sd_id_list_alter_daytemplate_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytemplate',
            name='sd_id_list',
        ),
    ]
