# Generated by Django 4.2.1 on 2023-05-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0030_remove_daytemplate_sd_id_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytemplate',
            name='cycle_copy_of',
            field=models.ManyToManyField(related_name='cycle_copies', to='empl.daytemplate'),
        ),
        migrations.AddField(
            model_name='daytemplate',
            name='primary_cycle',
            field=models.BooleanField(default=False),
        ),
    ]
