# Generated by Django 4.2.1 on 2023-05-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0031_daytemplate_cycle_copy_of_daytemplate_primary_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytemplate',
            name='cycle_copy_of',
        ),
        migrations.AddField(
            model_name='daytemplate',
            name='cycle_analog_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_copies', to='empl.daytemplate'),
        ),
    ]
