# Generated by Django 4.2.1 on 2023-05-29 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0032_remove_daytemplate_cycle_copy_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytemplate',
            name='cycle_analog_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='empl.daytemplate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='template_size',
            field=models.IntegerField(choices=[(2, '2-Week Cycle'), (3, '3-Week Cycle')], default=2, help_text='Template Size determines the frequency of repetition on assigning a template to schedule.If the employee is to work every other weekend, for example, a 2-week size would be appropriate.'),
        ),
    ]
