# Generated by Django 4.2.1 on 2023-06-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0037_alter_slot_state_delete_weeksummary'),
        ('empl', '0034_ptorequest_prd_id_ptorequest_wk_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='std_slot_size',
            field=models.IntegerField(default=10, help_text='The Hour value of a standard shift, this ensures that employees are Scheduled the amount of hours they deserve.'),
        ),
        migrations.CreateModel(
            name='EmployeeWeekMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wk_id', models.SmallIntegerField()),
                ('goal', models.PositiveSmallIntegerField()),
                ('hours', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_monitors', to='empl.employee')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_monitors', to='cal.version')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayPeriodMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_id', models.SmallIntegerField()),
                ('goal', models.PositiveSmallIntegerField()),
                ('hours', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_period_monitors', to='empl.employee')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_period_monitors', to='cal.version')),
            ],
        ),
    ]
