# Generated by Django 4.2.1 on 2023-06-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0038_alter_fillswith_options_and_more'),
        ('empl', '0037_employee_user_alter_daytemplateset_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytemplateset',
            name='versions',
            field=models.ManyToManyField(related_name='template_sets', to='cal.version'),
        ),
    ]
