# Generated by Django 4.2.1 on 2023-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0038_alter_fillswith_options_and_more'),
        ('empl', '0038_daytemplateset_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayperiodmonitor',
            name='slots',
            field=models.ManyToManyField(related_name='prd_monitors', to='cal.slot'),
        ),
    ]
