# Generated by Django 4.2.1 on 2023-06-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0039_employeepayperiodmonitor_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayperiodmonitor',
            name='state',
            field=models.CharField(choices=[('S', 'Seeking'), ('C', 'Content'), ('P', 'Polling')], default='S', max_length=1),
        ),
    ]
