# Generated by Django 4.2.1 on 2023-06-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0040_employeepayperiodmonitor_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='linked_account',
        ),
    ]
