# Generated by Django 4.2.1 on 2023-06-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0041_remove_employee_linked_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytemplateset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
