# Generated by Django 4.2.1 on 2023-06-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0044_alter_schedule_department'),
        ('empl', '0043_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeweekmonitor',
            name='slots',
            field=models.ManyToManyField(related_name='wk_monitors', to='cal.slot'),
        ),
        migrations.AddField(
            model_name='employeeweekmonitor',
            name='state',
            field=models.CharField(choices=[('S', 'Seeking'), ('C', 'Content'), ('P', 'Polling')], default='S', max_length=1),
        ),
    ]
