# Generated by Django 4.2.1 on 2023-06-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0044_employeeweekmonitor_slots_employeeweekmonitor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeweekmonitor',
            name='period_monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_monitors', to='empl.employeepayperiodmonitor'),
        ),
        migrations.AlterField(
            model_name='employeepayperiodmonitor',
            name='state',
            field=models.CharField(choices=[('S', 'Seeking'), ('I', 'Inactive'), ('P', 'Polling')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='employeeweekmonitor',
            name='state',
            field=models.CharField(choices=[('S', 'Seeking'), ('I', 'Inactive'), ('P', 'Polling')], default='S', max_length=1),
        ),
    ]
