# Generated by Django 4.2.1 on 2023-06-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0045_employeeweekmonitor_period_monitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayperiodmonitor',
            name='goal',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='employeeweekmonitor',
            name='goal',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
